on: workflow_call

jobs:
  test:
    environment: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npx nyc --reporter json --report-dir nyc_coverage --check-coverage false npm run test
      - uses: actions/upload-artifact@v7
        with:
          name: nyc_coverage
          path: nyc_coverage/