name: PR Tests
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/job-build.yml

  test:
    uses: ./.github/workflows/job-test.yml

  coverage:
    needs: test
    uses: ./.github/workflows/job-coverage.yml
